### ISSUE TITLE
Tester srvz-webapp

### ISSUE THREAD

**Issue by greut** [LucasBeltrame/Avedis#1]
Voir: HE-Arc/webapp-server#3.

Et merci d'ajouter David (@grunenwald ) ainsi que moi-même comme contributeurs du projet.

**Comment by LucasBeltrame** [comment]
Je viens de vous ajouter comme contributeurs du projet !

Et j'ai aussi testé et réussi à me connecter sur le serveur.

**Comment by greut** [comment]
Merci bien.
